version: "3"

services:
  
  db:
    image: postgres:13.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - sdump_pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
      
  dumps:
    tty: true
    image: sdump_dumps:latest
    restart: always
    environment:
      DUMPSERVER_USER: dumpserver
      DUMPSERVER_PASSWORD: pass
    volumes:
      - sdump_dumps:/srv/dumps
  
  sdump:
    restart: always
#    build: .
    image: sdump:latest
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env.dev
    volumes:
      - .:/srv/sdump
      - sdump_dumps:/srv/dumps
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  sdump_pgdata:
    external: true
  sdump_dumps:
    external: true
