# docker build -f container-build/dumps/Dockerfile -t dumps:latest .
# docker build -f container-build/sdump/Dockerfile -t sdump:latest .


version: "3"

services:
  
  db:
    image: postgres:13.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - sdump_pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
      
  dumps: 
    build:
      context: .
      dockerfile: container-build/dumps/Dockerfile
    restart: always
    env_file:
      - .env.dev
    volumes:
      - sdump_dumps:/srv/dumps
      - sdump_dumps_conf:/srv/dumps.conf.d
  
  sdump:
    build:
      context: .
      dockerfile: container-build/sdump/Dockerfile
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env.dev
    volumes:
      - .:/srv/sdump
      - sdump_dumps:/srv/dumps
      - sdump_dumps_conf:/srv/dumps.conf.d
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  sdump_pgdata:
    external: true
  sdump_dumps:
    external: true
  sdump_dumps_conf:
    external: true
