# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_added_blank_attribute_for_nullable_fields'),
    ]

    operations = [
        migrations.RunSQL("update django_content_type set app_label='app' \
        where app_label='dumpserver'"),
        migrations.RunSQL("update django_migrations set app='app' \
        where app='dumpserver'")
    ]
