# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_change_meta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base',
            options={'verbose_name': 'Base de Datos', 'verbose_name_plural': 'Bases de datos'},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'Versi\xf3n', 'verbose_name_plural': 'Versiones'},
        ),
        migrations.AlterField(
            model_name='base',
            name='contrasenia',
            field=models.CharField(max_length=100, verbose_name='contrase\xf1a'),
        ),
        migrations.AlterField(
            model_name='base',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='base',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Grupo', verbose_name='grupo'),
        ),
        migrations.AlterField(
            model_name='base',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='base',
            name='servidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Servidor', verbose_name='Servidor'),
        ),
        migrations.AlterField(
            model_name='base',
            name='usuario',
            field=models.CharField(max_length=100, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='directorio',
            field=models.CharField(max_length=255, null=True, verbose_name='Directorio'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ip'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='motor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='motor'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='puerto',
            field=models.IntegerField(blank=True, null=True, verbose_name='puerto'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Version', verbose_name='versi\xf3n'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='grupos',
            field=models.ManyToManyField(to='app.Grupo', verbose_name='grupo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=100, unique=True, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='version',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
    ]
