# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_fields_and_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='extra_command_options',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Opciones extras del comando'),
        ),
    ]
