# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_base_extra_command_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base',
            options={'verbose_name': 'Base de datos', 'verbose_name_plural': 'Bases de datos'},
        ),
    ]
