# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_change_meta_options_on_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='password_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='password_id'),
        ),
    ]
