# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_add_field_periodic_dump_to_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='periodic_dump',
            field=models.BooleanField(default=False, verbose_name='Dumps peri\xf3dicos'),
        ),
    ]
