# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_field_periodic_dump'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='last_date_download',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last_date_download'),
        ),
    ]
