# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_add_last_date_download_to_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='last_date_download',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha \xfaltima descarga'),
        ),
    ]
