# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-30 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_Alter_field_last_date_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='contrasenia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='contrase\xf1a'),
        ),
        migrations.AlterField(
            model_name='base',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='usuario'),
        ),
    ]
