# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-23 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_field_contrasenia_and_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='alow_sharing',
            field=models.BooleanField(default=False, verbose_name='alow_sharing'),
        ),
    ]
