# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-23 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_add_field_alow_sharing_to_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='alow_sharing',
            field=models.BooleanField(default=False, verbose_name='Permitir compartir'),
        ),
    ]
