# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-23 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_field_alow_sharing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shared',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254, verbose_name='nombre')),
                ('hash', models.CharField(max_length=254, verbose_name='funci\xf3n resumen')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Base', verbose_name='database')),
            ],
            options={
                'db_table': 'shares',
                'verbose_name': 'Share',
                'verbose_name_plural': 'Shares',
            },
        ),
    ]
