# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-23 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_create_model_shared'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='share',
            options={'verbose_name': 'Compartir', 'verbose_name_plural': 'Compartidos'},
        ),
        migrations.AlterField(
            model_name='share',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Base', verbose_name='Base de datos'),
        ),
        migrations.AlterField(
            model_name='share',
            name='hash',
            field=models.CharField(max_length=254, verbose_name='hash'),
        ),
    ]
