# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_permissions_for_user_on_share'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base',
            options={'ordering': ['nombre'], 'verbose_name': 'Base de datos', 'verbose_name_plural': 'Bases de datos'},
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['nombre'], 'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterModelOptions(
            name='servidor',
            options={'ordering': ['nombre'], 'verbose_name': 'Servidor', 'verbose_name_plural': 'Servidores'},
        ),
        migrations.AlterModelOptions(
            name='share',
            options={'ordering': ['name'], 'verbose_name': 'Compartir', 'verbose_name_plural': 'Compartidos'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nombre'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['nombre'], 'verbose_name': 'Versi\xf3n', 'verbose_name_plural': 'Versiones'},
        ),
    ]
